### ISSUE TITLE
Low-level Network Communication

### ISSUE THREAD

**Issue by Nitrodist** [darcymiranda/revert#11]
http://code.google.com/p/protobuf/

Found this. What do you guys think?

**Comment by darcymiranda** [comment]
I am thinking we should have a static class that abstracts out all of the packet creation.

Example:

ActionSender.shootMissile(Entity e);
ActionSender.chat("oh hello");

Have the class create the messages with your fancy protocol that you found

**Comment by Nitrodist** [comment]
Are these asynchronous?

**Comment by darcymiranda** [comment]
What do you mean by 'these'?

**Comment by Nitrodist** [comment]
The calls to those methods.

**Comment by darcymiranda** [comment]
They would not be. No point, honestly.

I mean that ActionSender would replace this:

p = new Packet()/new Message()

p.id = 0
p.x = 55
p.y = 55
p.othercrap = s7dg7sd9gd

with... ActionSender.sendMovement(Entity e)
