### ISSUE TITLE
Bullet origin does not rotate with ship

### ISSUE THREAD

**Issue by Nitrodist** [darcymiranda/revert#13]
Bullets shot originate from the same position no matter which direction you're facing so when they're shot at certain angles, they appear on the same path instead of side by side like they would if you were rotate a real ship and fire.

http://imgur.com/7Eu5c

http://imgur.com/6sU7C

**Comment by darcymiranda** [comment]
Yeah this is a known bug and an easy fix. I don't believe the server is calculating the position of the bullet the same way the client is.

**Comment by darcymiranda** [comment]
I looked at the calculations that the client and server uses and they're the same; but there is probably something i missed. THE HORRORS OF DUPLICATE CODE PEOPLE -- really have to put some time into sorted out that mess..........later =P
