### ISSUE TITLE
Client/Server Bullets

### ISSUE THREAD

**Issue by darcymiranda** [darcymiranda/revert#5]
Currently, if the a player presses and releases the fire button really quick, other clients won't see a bullet fire. This is because it happens in less than the amount of time in-between packet sends.

**Comment by Nitrodist** [comment]
So it doesn't send on the next packet?

**Comment by darcymiranda** [comment]
It's because the packet that tells the clients when a player is shooting is queued in an interval, so it could change, in between the interval time and other players won't know.

I am just going to go back to how I was queue packets before, with the ActionSender class. I'll just make it static and remove all getPacket methods. This way I won't have the limitation of only being able to queue up packets in the game loop...

**Comment by darcymiranda** [comment]
Fixed. Packets containing if keys are pressed or released will be queued as soon as it's changed, instead of using interval that ship updates use.
