### ISSUE TITLE
Ship movement

### ISSUE THREAD

**Issue by Scatt** [darcymiranda/revert#7]
The ship's movement is off. I didn't notice it at first but since you added the print out of the velocities it's very obvious. 

For example:

If you are going right, and a tiny bit down, the x vel is goes to 5 and the y vel eventually creeps up to 5 as well, which should not happen. Xvel should only be 5 if you are going completely right or left as wel as Yvel being 5 for going completely up/down.

Going to need to look into it.

**Comment by Nitrodist** [comment]
5 is max velocity right?

**Comment by Scatt** [comment]
To make things clearer:

Say you're going completely right (90 degrees) then you go a little bit down (100 degrees), Yvel keeps adding so even though you're aimed at "100 degrees" you'll end up going 135 degrees. Which is bad.

**Comment by darcymiranda** [comment]
The code for this was pulled off the original revision of Revert, so it's fairly old and crappy :)

**Comment by darcymiranda** [comment]
Made same mistake as you Mark, WHY IS THE CLOSE BUTTON THERE

**Comment by Nitrodist** [comment]
LOL, I know!

**Comment by darcymiranda** [comment]
Who volunteers to redo my HORRIBLE movement code? That shit is dated and needs to be re-done.

**Comment by darcymiranda** [comment]
Scatt is working on it.

**Comment by darcymiranda** [comment]
Scatt tried to fix it up with his own re-write and different methodology with no success. It looks like we will just comment it out for now, go back to my old code and just patch it up the best we can.
