### ISSUE TITLE
Server/Client Sync

### ISSUE THREAD

**Issue by darcymiranda** [darcymiranda/revert#9]
I can't figure out a way for the bullets to be the same speed, on both the client and the server. I am trying to have the client only send the position/velocity of the bullet once, as soon it's fired and have the server compute the position changes that based on the velocity.

There isn't that much information about this and I think we should calibrated a resolution.

Idea that I am thinking of:

Take the speed that client deltas are trying to sustain, find the average and _somehow_ have it modified to fit the server's "FPS".

**Comment by Scatt** [comment]
whats the issue right now? because it should work if you're passing the position/velocity once it has been shot

**Comment by Scatt** [comment]
oh im guessing you need to pass delta too? or ya get an average of the delta's although that won't be accurate, so..

**Comment by darcymiranda** [comment]
Yep, and you do NOT want to send the delta to the server because the delta will be different for each client.

**Comment by darcymiranda** [comment]
I need to find out what the delta is for 60 fps and use that with the server, I think...

**Comment by Scatt** [comment]
it will still be off though
